window.RESTORATION_ROUTE_DATA = {
  "assets": {
    "home": "assets/home_ui.webp",
    "menu": "assets/menu_ui.webp",
    "scanner": "assets/scanner_ui.webp",
    "directory": "assets/8_venue_assets_garage_directory_ui.webp",
    "venue1": "assets/venue_1_ui.jpg",
    "venue2": "assets/venue_2_ui.jpg",
    "venue3": "assets/venue_3_ui.jpg",
    "venue4": "assets/venue_4_ui.jpg",
    "venue5": "assets/venue_5_ui.jpg",
    "venue6": "assets/venue_6_ui.jpg",
    "venue7": "assets/venue_7_ui.jpg",
    "venue8": "assets/venue_8_ui.jpg",
    "serviceBook": "assets/garage_directory_exact_from_json.webp",
    "wallMap": "assets/wall_map_exact_from_json.webp",
    "scannerTool": "assets/component_assets_scanner_tool_transparent.webp",
    "scannerHomeButton": "assets/scanner_home_button.png",
    "homeButton": "assets/garage_directory_assets_home_button.webp",
    "repairStamp": "assets/garage_directory_assets_repaired_stamp.webp",
    "manCaveTab": "assets/garage_directory_assets_directory_tab_buttons_the_man_cave_tab_button.png",
    "banterBox": "assets/banter_box.webp",
    "audio": {
      "horn": "assets/horn_noise.mp3"
    },
    "menuButtons": {
      "profile": "assets/menu_buttons_restoration_route_button_profile_true_alpha.webp",
      "leaderboard": "assets/menu_buttons_restoration_route_button_leaderboard_true_alpha.webp",
      "issues": "assets/menu_buttons_restoration_route_button_issues_true_alpha.webp",
      "logout": "assets/menu_buttons_restoration_route_button_log_out_true_alpha.webp"
    },
    "completionBrokenVehicle": "assets/vehicle_broken_placeholder.png",
    "completionFixedVehicle": "assets/vehicle_fixed_placeholder.png"
  },
  "components": {
    "engine": {
      "broken": "assets/engine_damaged_true_transparent.webp",
      "fixed": "assets/engine_repaired_true_transparent.webp"
    },
    "oil_filter": {
      "broken": "assets/component_assets_oil_filter_broken.webp",
      "fixed": "assets/component_assets_oil_filter_fixed.png"
    },
    "wheel": {
      "broken": "assets/component_assets_wheel_broken.png",
      "fixed": "assets/component_assets_wheel_fixed.png"
    },
    "headlight": {
      "broken": "assets/component_assets_headlight_broken.png",
      "fixed": "assets/component_assets_headlight_fixed.png"
    },
    "gearbox": {
      "broken": "assets/component_assets_gearbox_broken.webp",
      "fixed": "assets/component_assets_gearbox_fixed.png"
    },
    "exhaust": {
      "broken": "assets/component_assets_exhaust_broken.png",
      "fixed": "assets/component_assets_exhaust_fixed.png"
    },
    "fuel_tank": {
      "broken": "assets/component_assets_fuel_tank_broken.png",
      "fixed": "assets/component_assets_fuel_tank_fixed.png"
    },
    "radiator": {
      "broken": "assets/component_assets_radiator_broken.webp",
      "fixed": "assets/component_assets_radiator_fixed.webp"
    },
    "horn": {
      "broken": "assets/component_assets_horn_broken.png",
      "fixed": "assets/component_assets_horn_fixed.png"
    },
    "vehicle": {
      "broken": "assets/vehicle_broken_placeholder.png",
      "fixed": "assets/vehicle_fixed_placeholder.png"
    }
  },
  "venues": [
    {
      "id": "piston-club",
      "name": "The Piston Club",
      "component": "Engine",
      "key": "engine",
      "page": "venue1",
      "specialist": "Specialists in classic engine repair and replacement parts.",
      "summary": [
        "A motoring-themed venue and route base for classic-car fans.",
        "The engine is the heart of the restoration.",
        "Scan here to bring the motor back to life."
      ],
      "address": [
        "The Piston Club @ The Stag",
        "Alcester Road, Redhill",
        "Stratford-upon-Avon B49 6NQ"
      ],
      "opening": [
        "7:30am \u2013 10pm",
        "7:30am \u2013 10pm",
        "7:30am \u2013 10pm",
        "7:30am \u2013 10pm",
        "7:30am \u2013 10pm",
        "7:30am \u2013 10pm",
        "7:30am \u2013 8pm"
      ],
      "food": [
        "7:30am \u2013 9pm",
        "7:30am \u2013 9pm",
        "7:30am \u2013 9pm",
        "7:30am \u2013 9pm",
        "7:30am \u2013 9pm",
        "7:30am \u2013 9pm",
        "7:30am \u2013 7pm"
      ],
      "notes": [
        "Engine logged through The Piston Club.",
        "A restored engine brings the project alive.",
        ""
      ],
      "website": "thepistonclub.co.uk",
      "phone": "01789 740266",
      "email": "info@thepistonclub.co.uk"
    },
    {
      "id": "oily-rag",
      "name": "Oily Rag",
      "component": "Oil Filter",
      "key": "oil_filter",
      "page": "venue4",
      "specialist": "Specialists in lubrication parts, filter housings and oily essentials.",
      "summary": [
        "A garage-culture stop with a proper oily-rag feel.",
        "This venue handles filtration and lubrication.",
        "Scan here to repair the oil filter."
      ],
      "address": [
        "Oily Rag HQ",
        "Unit 9 Rockhaven, Triangle Park",
        "Gloucester GL1 1AJ"
      ],
      "opening": [
        "Closed",
        "Closed",
        "Closed",
        "Closed",
        "10am - 4pm",
        "10am - 4pm",
        "10am - 2:30pm"
      ],
      "food": [
        "Closed",
        "Closed",
        "Closed",
        "Closed",
        "Coffee / shop hours",
        "Coffee / shop hours",
        "Coffee / shop hours"
      ],
      "notes": [
        "Fresh filtration keeps the old engine protected.",
        "No oil flow, no route.",
        ""
      ],
      "website": "oilyrag.com",
      "phone": "07780 000056",
      "email": "info@oilyrag.com"
    },
    {
      "id": "seven-mile",
      "name": "Seven Mile",
      "component": "Wheels",
      "key": "wheel",
      "page": "venue7",
      "specialist": "Specialists in wheels, tyres and getting the car rolling again.",
      "summary": [
        "Seven Mile keeps the route moving.",
        "This stop handles the wheel repair.",
        "Scan here to get the car rolling properly."
      ],
      "address": [
        "Seven Mile Cookery & Events",
        "Cotswolds & Midlands catering",
        "By enquiry / event booking"
      ],
      "opening": [
        "By enquiry",
        "By enquiry",
        "By enquiry",
        "By enquiry",
        "By enquiry",
        "By enquiry",
        "By enquiry"
      ],
      "food": [
        "Event catering",
        "Event catering",
        "Event catering",
        "Event catering",
        "Event catering",
        "Event catering",
        "Event catering"
      ],
      "notes": [
        "Good wheels turn a static project into a moving car.",
        "The route needs grip.",
        ""
      ],
      "website": "sevenmile.co.uk",
      "phone": "07807 939952",
      "email": "hello@sevenmile.co.uk"
    },
    {
      "id": "mr-watsons",
      "name": "Mr. Watson\u2019s",
      "component": "Headlights",
      "key": "headlight",
      "page": "venue2",
      "specialist": "Specialists in classic lamps, lenses and lighting restoration.",
      "summary": [
        "Mr. Watson\u2019s handles visibility and lighting.",
        "This stop restores the headlight.",
        "Scan here to light the way ahead."
      ],
      "address": [
        "Mr. Watson\u2019s Cafe",
        "72 Northwick Business Centre",
        "Blockley GL56 9RF"
      ],
      "opening": [
        "10:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "10am - 2pm*",
        "Closed"
      ],
      "food": [
        "10:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "10am - 2pm*",
        "Closed"
      ],
      "notes": [
        "A working headlight makes the restoration road-ready.",
        "*Saturday openings vary; check Facebook.",
        ""
      ],
      "website": "mrwatsonscafe.com",
      "phone": "01386 700907",
      "email": "mrwatsonscafe@gmail.com"
    },
    {
      "id": "gilks-garage",
      "name": "Gilks\u2019 Garage",
      "component": "Gearbox",
      "key": "gearbox",
      "page": "venue3",
      "specialist": "Specialists in gearbox and transmission repair.",
      "summary": [
        "Gilks\u2019 Garage handles the mechanical shifting.",
        "This stop restores the gearbox.",
        "Scan here to smooth out the transmission."
      ],
      "address": [
        "Gilks\u2019 Garage Caf\u00e9",
        "Banbury Road, Kineton",
        "Warwickshire CV35 0JZ"
      ],
      "opening": [
        "Closed",
        "Closed",
        "9am \u2013 3pm",
        "9am \u2013 3pm",
        "9am \u2013 3pm",
        "9am \u2013 3pm",
        "9am \u2013 3pm"
      ],
      "food": [
        "Closed",
        "Closed",
        "9am \u2013 3pm",
        "9am \u2013 3pm",
        "9am \u2013 3pm",
        "9am \u2013 3pm",
        "9am \u2013 3pm"
      ],
      "notes": [
        "A restored gearbox gets power to the road properly.",
        "Smooth shifts keep the car moving.",
        ""
      ],
      "website": "gilksgaragecafe.com",
      "phone": "01926 640539",
      "email": "info@gilksgaragecafe.com"
    },
    {
      "id": "long-itch-diner",
      "name": "The Long Itch Diner",
      "component": "Exhaust",
      "key": "exhaust",
      "page": "venue5",
      "specialist": "Specialists in exhaust routing, silencers and pipe replacement.",
      "summary": [
        "The Long Itch Diner handles the exhaust system.",
        "This stop gets the car breathing properly.",
        "Scan here to repair the exhaust."
      ],
      "address": [
        "The Long Itch Diner",
        "Southam Road, Long Itchington",
        "Southam CV47 9QZ"
      ],
      "opening": [
        "8:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "9am - 3pm"
      ],
      "food": [
        "8:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "8:30am - 3pm",
        "9am - 3pm"
      ],
      "notes": [
        "A sorted exhaust makes the car sound alive again.",
        "Less rattle, more route.",
        ""
      ],
      "website": "longitchdiner.co.uk",
      "phone": "01926 819096",
      "email": ""
    },
    {
      "id": "pats-baps",
      "name": "Pat\u2019s Baps",
      "component": "Fuel Tank",
      "key": "fuel_tank",
      "page": "venue6",
      "specialist": "Specialists in fuel tank replacement and fuel-system basics.",
      "summary": [
        "Pat\u2019s Baps handles fuel supply for the build.",
        "This stop restores the fuel tank.",
        "Scan here to get fuel back in the car."
      ],
      "address": [
        "Cotswold Cafe / Pat\u2019s Baps",
        "London Road, Little Compton",
        "Moreton-in-Marsh GL56 0RR"
      ],
      "opening": [
        "9am - 3pm",
        "9am - 3pm",
        "9am - 3pm",
        "9am - 3pm",
        "9am - 3pm",
        "9am - 1pm",
        "Closed"
      ],
      "food": [
        "9am - 3pm",
        "9am - 3pm",
        "9am - 3pm",
        "9am - 3pm",
        "9am - 3pm",
        "9am - 1pm",
        "Closed"
      ],
      "notes": [
        "No tank, no tour.",
        "This repair gets fuel back in the game.",
        ""
      ],
      "website": "cotswoldcafe-patsbaps.co.uk",
      "phone": "01608 674729",
      "email": "cotswoldcafe@hotmail.com"
    },
    {
      "id": "the-man-cave",
      "name": "The Man Cave",
      "component": "Radiator",
      "key": "radiator",
      "page": "venue8",
      "specialist": "Specialists in radiator repair, cooling and heat control.",
      "summary": [
        "The Man Cave keeps the engine cool.",
        "This stop restores the radiator.",
        "Scan here to repair the cooling system."
      ],
      "address": [
        "The Man Cave Broadway",
        "Dickens House, 20 High Street",
        "Broadway WR12 7DT"
      ],
      "opening": [
        "10am - 5pm",
        "10am - 5pm",
        "10am - 5pm",
        "10am - 5pm",
        "10am - 5pm",
        "10am - 5pm",
        "10am - 5pm"
      ],
      "food": [
        "N/A",
        "N/A",
        "N/A",
        "N/A",
        "N/A",
        "N/A",
        "N/A"
      ],
      "notes": [
        "Cooling keeps the restored engine safe.",
        "The radiator finishes the route system.",
        ""
      ],
      "website": "themancavebroadway.co.uk",
      "phone": "01386 244560",
      "email": "info@TMCBroadway.co.uk"
    }
  ],
  "layout": {
    "home": {
      "id": "page_home",
      "name": "Home",
      "stage": {
        "width": 390,
        "height": 844
      },
      "layers": [
        {
          "id": "layer_home_background",
          "type": "image",
          "name": "Home UI",
          "src": "assets/home_ui.webp",
          "x": -29,
          "y": -1,
          "w": 485,
          "h": 845,
          "r": 0,
          "opacity": 1,
          "locked": true,
          "z": 0,
          "assetCategory": "Screen Backgrounds"
        },
        {
          "id": "layer_mp76saea_1000",
          "type": "image",
          "name": "Exhaust Broken",
          "src": "assets/component_assets_exhaust_broken.png",
          "x": 162,
          "y": 623,
          "w": 236,
          "h": 170,
          "r": 13,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 1,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp76sp6j_1001",
          "type": "image",
          "name": "Fuel Tank Broken",
          "src": "assets/component_assets_fuel_tank_broken.png",
          "x": -19,
          "y": 662,
          "w": 185,
          "h": 89,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 2,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp76svft_1002",
          "type": "image",
          "name": "Horn Fixed",
          "src": "assets/component_assets_horn_fixed.png",
          "x": 4,
          "y": 752,
          "w": 137,
          "h": 83,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 3,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp76tvi0_1004",
          "type": "image",
          "name": "Headlight Broken",
          "src": "assets/component_assets_headlight_broken.png",
          "x": 127,
          "y": 493,
          "w": 66,
          "h": 34,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 4,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp774ovk_1006",
          "type": "image",
          "name": "Oil Filter Broken",
          "src": "assets/component_assets_oil_filter_broken.webp",
          "x": 180,
          "y": 667,
          "w": 41,
          "h": 73,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 5,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp774pns_1007",
          "type": "image",
          "name": "Radiator Broken",
          "src": "assets/component_assets_radiator_broken.webp",
          "x": 83,
          "y": 559,
          "w": 109,
          "h": 93,
          "r": -5,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 6,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp774ri0_1008",
          "type": "image",
          "name": "Wheel Broken",
          "src": "assets/component_assets_wheel_broken.png",
          "x": 264,
          "y": 452,
          "w": 133,
          "h": 102,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 7,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp775zj5_1009",
          "type": "image",
          "name": "Banter Box",
          "src": "assets/banter_box.webp",
          "x": 302,
          "y": 347,
          "w": 80,
          "h": 105,
          "r": 2,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 8,
          "assetCategory": "Root Assets"
        },
        {
          "id": "layer_mp77y2bw_1024",
          "type": "image",
          "name": "Garage Directory.png",
          "src": "blob:null/89e426f4-ab06-45a1-afaa-ad28b191d76b",
          "x": 116,
          "y": 349,
          "w": 90,
          "h": 31,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 9,
          "assetCategory": "Imported"
        },
        {
          "id": "layer_mp77y2c2_1025",
          "type": "image",
          "name": "Wall Map.png",
          "src": "blob:null/563aad8f-44dc-47a7-bad5-da6c60c28263",
          "x": 121,
          "y": 157,
          "w": 100,
          "h": 173,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 10,
          "assetCategory": "Imported"
        },
        {
          "id": "layer_mp7825hm_1026",
          "type": "image",
          "name": "Scanner Tool.png",
          "src": "blob:null/f713e94f-145e-4b88-88c6-899826566d49",
          "x": 300,
          "y": 706,
          "w": 74,
          "h": 166,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 11,
          "assetCategory": "Imported"
        },
        {
          "id": "layer_mp8qe7ti_1070",
          "type": "image",
          "name": "Gearbox Broken",
          "src": "assets/component_assets_gearbox_broken.webp",
          "x": -10,
          "y": 517,
          "w": 129,
          "h": 89,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 12,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp8qfsaf_1072",
          "type": "image",
          "name": "engine_damaged_true_transparent.png",
          "src": "blob:null/6f8220e3-821f-4992-ba1a-76ec53d68f56",
          "x": 170,
          "y": 485,
          "w": 139,
          "h": 193,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 13,
          "assetCategory": "Imported"
        }
      ]
    },
    "menu": {
      "id": "page_menu",
      "name": "Menu",
      "stage": {
        "width": 390,
        "height": 844
      },
      "layers": [
        {
          "id": "layer_menu_background",
          "type": "image",
          "name": "Menu UI",
          "src": "assets/menu_ui.webp",
          "x": 0,
          "y": -39,
          "w": 390,
          "h": 844,
          "r": 0,
          "opacity": 1,
          "locked": true,
          "z": 0,
          "assetCategory": "Screen Backgrounds"
        },
        {
          "id": "layer_mp7792jg_1010",
          "type": "image",
          "name": "Restoration Route Button Issues True Alpha",
          "src": "assets/menu_buttons_restoration_route_button_issues_true_alpha.webp",
          "x": -12,
          "y": 350,
          "w": 413,
          "h": 124,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 1,
          "assetCategory": "Menu Buttons"
        },
        {
          "id": "layer_mp779bsb_1013",
          "type": "image",
          "name": "Restoration Route Button Profile True Alpha",
          "src": "assets/menu_buttons_restoration_route_button_profile_true_alpha.webp",
          "x": 6,
          "y": 148,
          "w": 376,
          "h": 119,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 2,
          "assetCategory": "Menu Buttons"
        },
        {
          "id": "layer_mp77d70i_1014",
          "type": "image",
          "name": "Restoration Route Button Leaderboard True Alpha",
          "src": "assets/menu_buttons_restoration_route_button_leaderboard_true_alpha.webp",
          "x": 7,
          "y": 283,
          "w": 376,
          "h": 119,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 3,
          "assetCategory": "Menu Buttons"
        },
        {
          "id": "layer_mp77gh8p_1015",
          "type": "image",
          "name": "Restoration Route Button Log Out True Alpha",
          "src": "assets/menu_buttons_restoration_route_button_log_out_true_alpha.webp",
          "x": 7,
          "y": 216,
          "w": 376,
          "h": 119,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 4,
          "assetCategory": "Menu Buttons"
        }
      ]
    },
    "scanner": {
      "id": "page_scanner",
      "name": "Scanner",
      "stage": {
        "width": 390,
        "height": 844
      },
      "layers": [
        {
          "id": "layer_scanner_background",
          "type": "image",
          "name": "Scanner UI",
          "src": "assets/scanner_ui.webp",
          "x": -48,
          "y": 1,
          "w": 486,
          "h": 843,
          "r": 0,
          "opacity": 1,
          "locked": false,
          "z": 0,
          "assetCategory": "Screen Backgrounds"
        },
        {
          "id": "layer_mp79g99v_1069",
          "type": "image",
          "name": "Scanner Home Button.png",
          "src": "blob:null/8abedd73-7bc4-48e6-8f02-748cb582f12e",
          "x": 263,
          "y": 505,
          "w": 103,
          "h": 52,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 1,
          "assetCategory": "Imported"
        }
      ]
    },
    "directory": {
      "id": "page_garage_directory",
      "name": "Garage Directory",
      "stage": {
        "width": 390,
        "height": 844
      },
      "layers": [
        {
          "id": "layer_mp8stt2h_1084",
          "type": "image",
          "name": "Garage Directory UI.png",
          "src": "blob:null/db437488-5340-4a1a-bc16-7e0da45eaaf3",
          "x": -32,
          "y": 183,
          "w": 452,
          "h": 493,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 0,
          "assetCategory": "Imported"
        },
        {
          "id": "layer_mp77jay8_1018",
          "type": "image",
          "name": "Garage Directory Tab Button",
          "src": "assets/garage_directory_assets_directory_tab_buttons_garage_directory_tab_button.png",
          "x": 351,
          "y": 199,
          "w": 32,
          "h": 66,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 1,
          "assetCategory": "Garage Directory Tab Buttons"
        },
        {
          "id": "layer_mp77jeae_1023",
          "type": "image",
          "name": "The Piston Club Tab Button",
          "src": "assets/garage_directory_assets_directory_tab_buttons_the_piston_club_tab_button.png",
          "x": 351,
          "y": 251,
          "w": 32,
          "h": 60,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 2,
          "assetCategory": "Garage Directory Tab Buttons"
        },
        {
          "id": "layer_mp77jacz_1017",
          "type": "image",
          "name": "Mr Watsons Tab Button",
          "src": "assets/garage_directory_assets_directory_tab_buttons_mr_watsons_tab_button.png",
          "x": 351,
          "y": 299,
          "w": 32,
          "h": 60,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 3,
          "assetCategory": "Garage Directory Tab Buttons"
        },
        {
          "id": "layer_mp77j90r_1016",
          "type": "image",
          "name": "Gilks' Garage Tab Button",
          "src": "assets/garage_directory_assets_directory_tab_buttons_gilks_garage_tab_button.png",
          "x": 354,
          "y": 353,
          "w": 27,
          "h": 48,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 4,
          "assetCategory": "Garage Directory Tab Buttons"
        },
        {
          "id": "layer_mp77jbxf_1020",
          "type": "image",
          "name": "Oily Rag Tab Button",
          "src": "assets/garage_directory_assets_directory_tab_buttons_oily_rag_tab_button.png",
          "x": 352,
          "y": 394,
          "w": 32,
          "h": 60,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 5,
          "assetCategory": "Garage Directory Tab Buttons"
        },
        {
          "id": "layer_mp77jcht_1021",
          "type": "image",
          "name": "The Long Itch Diner Tab Button",
          "src": "assets/garage_directory_assets_directory_tab_buttons_the_long_itch_diner_tab_button.png",
          "x": 352,
          "y": 442,
          "w": 32,
          "h": 60,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 6,
          "assetCategory": "Garage Directory Tab Buttons"
        },
        {
          "id": "layer_mp77jbh8_1019",
          "type": "image",
          "name": "Pats Baps Tab Button",
          "src": "assets/garage_directory_assets_directory_tab_buttons_pats_baps_tab_button.png",
          "x": 352,
          "y": 490,
          "w": 32,
          "h": 60,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 7,
          "assetCategory": "Garage Directory Tab Buttons"
        },
        {
          "id": "layer_mp77jcxi_1022",
          "type": "image",
          "name": "Seven Mile Tab Button",
          "src": "assets/garage_directory_assets_directory_tab_buttons_seven_mile_tab_button.png",
          "x": 352,
          "y": 538,
          "w": 32,
          "h": 60,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 8,
          "assetCategory": "Garage Directory Tab Buttons"
        },
        {
          "id": "layer_mp795531_1067",
          "type": "image",
          "name": "Home Button",
          "src": "assets/garage_directory_assets_home_button.webp",
          "x": 251,
          "y": 208,
          "w": 96,
          "h": 36,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 9,
          "assetCategory": "Garage Directory Assets"
        },
        {
          "id": "layer_mp8qu3z9_1073",
          "type": "image",
          "name": "Exhaust Fixed",
          "src": "assets/component_assets_exhaust_fixed.png",
          "x": 122,
          "y": 480,
          "w": 24,
          "h": 52,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 10,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp8qu4hr_1074",
          "type": "image",
          "name": "Fuel Tank Fixed",
          "src": "assets/component_assets_fuel_tank_fixed.png",
          "x": 106,
          "y": 542,
          "w": 59,
          "h": 24,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 11,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp8qu4xy_1075",
          "type": "image",
          "name": "Gearbox Fixed",
          "src": "assets/component_assets_gearbox_fixed.png",
          "x": 114,
          "y": 396,
          "w": 41,
          "h": 28,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 12,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp8qu5cq_1076",
          "type": "image",
          "name": "Headlight Fixed",
          "src": "assets/component_assets_headlight_fixed.png",
          "x": 122,
          "y": 344,
          "w": 25,
          "h": 34,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 13,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp8qu6u0_1077",
          "type": "image",
          "name": "Oil Filter Fixed",
          "src": "assets/component_assets_oil_filter_fixed.png",
          "x": 127,
          "y": 439,
          "w": 19,
          "h": 39,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 14,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp8qu7v1_1078",
          "type": "image",
          "name": "Radiator Fixed",
          "src": "assets/component_assets_radiator_fixed.webp",
          "x": 124,
          "y": 627,
          "w": 23,
          "h": 39,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 15,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp8qu8j3_1079",
          "type": "image",
          "name": "Wheel Fixed",
          "src": "assets/component_assets_wheel_fixed.png",
          "x": 107,
          "y": 585,
          "w": 56,
          "h": 32,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 16,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp8qubhl_1080",
          "type": "image",
          "name": "engine_repaired_true_transparent.png",
          "src": "blob:null/3cf5a83b-53f0-4a88-8664-5cef017e066b",
          "x": 120,
          "y": 290,
          "w": 30,
          "h": 48,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 17,
          "assetCategory": "Imported"
        },
        {
          "id": "layer_mp8szol5_1087",
          "type": "image",
          "name": "2 the man cave Tab Button.png",
          "src": "blob:null/2421383b-c521-44cd-a10c-c8c0006b3771",
          "x": 355,
          "y": 588,
          "w": 27,
          "h": 53,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 18,
          "assetCategory": "Imported"
        },
        {
          "id": "layer_mp8t59bq_1088",
          "type": "text",
          "name": "Text",
          "src": null,
          "x": 54,
          "y": 297,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 19
        },
        {
          "id": "layer_mp8t5wx8_1089",
          "type": "text",
          "name": "Text copy",
          "src": null,
          "x": 53,
          "y": 342,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 20
        },
        {
          "id": "layer_mp8t62le_1090",
          "type": "text",
          "name": "Text copy copy",
          "src": null,
          "x": 52,
          "y": 394,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 21
        },
        {
          "id": "layer_mp8t69cy_1091",
          "type": "text",
          "name": "Text copy copy copy",
          "src": null,
          "x": 54,
          "y": 442,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 22
        },
        {
          "id": "layer_mp8t6dch_1092",
          "type": "text",
          "name": "Text copy copy copy copy",
          "src": null,
          "x": 54,
          "y": 489,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 23
        },
        {
          "id": "layer_mp8t6it7_1093",
          "type": "text",
          "name": "Text copy copy copy copy copy",
          "src": null,
          "x": 54,
          "y": 536,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 24
        },
        {
          "id": "layer_mp8t6lz3_1094",
          "type": "text",
          "name": "Text copy copy copy copy copy copy",
          "src": null,
          "x": 56,
          "y": 584,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 25
        },
        {
          "id": "layer_mp8t6pwc_1095",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy",
          "src": null,
          "x": 57,
          "y": 630,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 26
        },
        {
          "id": "layer_mp8t6wbe_1096",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 170,
          "y": 296,
          "w": 48,
          "h": 13,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 27
        },
        {
          "id": "layer_mp8t7918_1097",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 169,
          "y": 317,
          "w": 49,
          "h": 13,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 28
        },
        {
          "id": "layer_mp8t7ece_1098",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 170,
          "y": 334,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 29
        },
        {
          "id": "layer_mp8t7l22_1099",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 170,
          "y": 356,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 30
        },
        {
          "id": "layer_mp8t7ld6_1100",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 169,
          "y": 382,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 31
        },
        {
          "id": "layer_mp8t7lm0_1101",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 169,
          "y": 405,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 32
        },
        {
          "id": "layer_mp8t7ltu_1102",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 170,
          "y": 429,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 33
        },
        {
          "id": "layer_mp8t7m1q_1103",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 170,
          "y": 453,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 34
        },
        {
          "id": "layer_mp8t7ma2_1104",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 169,
          "y": 478,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 35
        },
        {
          "id": "layer_mp8t7mhh_1105",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 169,
          "y": 499,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 36
        },
        {
          "id": "layer_mp8t7mpc_1106",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 170,
          "y": 524,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 37
        },
        {
          "id": "layer_mp8t7mwl_1107",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 170,
          "y": 547,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 38
        },
        {
          "id": "layer_mp8t7n4x_1108",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 169,
          "y": 574,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 39
        },
        {
          "id": "layer_mp8t7ncc_1109",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 169,
          "y": 595,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 40
        },
        {
          "id": "layer_mp8t7njr_1110",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 170,
          "y": 620,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 41
        },
        {
          "id": "layer_mp8t90qi_1111",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 171,
          "y": 640,
          "w": 49,
          "h": 33,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 20,
          "color": "#0a3156",
          "locked": false,
          "z": 42
        },
        {
          "id": "layer_mp8t9eub_1112",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 238,
          "y": 294,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 43
        },
        {
          "id": "layer_mp8tbig5_1113",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 238,
          "y": 306,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 44
        },
        {
          "id": "layer_mp8tbimk_1114",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 238,
          "y": 319,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 45
        },
        {
          "id": "layer_mp8tbisv_1115",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 238,
          "y": 391,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 46
        },
        {
          "id": "layer_mp8tbiz1_1116",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 238,
          "y": 403,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 47
        },
        {
          "id": "layer_mp8tbj5l_1117",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 238,
          "y": 416,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 48
        },
        {
          "id": "layer_mp8tbjdf_1118",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 239,
          "y": 438,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 49
        },
        {
          "id": "layer_mp8tbjj9_1119",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 239,
          "y": 451,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 50
        },
        {
          "id": "layer_mp8tbjs8_1120",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 239,
          "y": 464,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 51
        },
        {
          "id": "layer_mp8tbkyu_1121",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 240,
          "y": 486,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 52
        },
        {
          "id": "layer_mp8tbxaw_1122",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 238,
          "y": 355,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 53
        },
        {
          "id": "layer_mp8tbxfy_1123",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 238,
          "y": 368,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 54
        },
        {
          "id": "layer_mp8tbxmr_1124",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 238,
          "y": 342,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 55
        },
        {
          "id": "layer_mp8tc5ys_1125",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 240,
          "y": 499,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 56
        },
        {
          "id": "layer_mp8tc65c_1126",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 240,
          "y": 512,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 57
        },
        {
          "id": "layer_mp8tc6kf_1127",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 240,
          "y": 534,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 58
        },
        {
          "id": "layer_mp8tc6qn_1128",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 240,
          "y": 547,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 59
        },
        {
          "id": "layer_mp8tc6xh_1129",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 240,
          "y": 560,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 60
        },
        {
          "id": "layer_mp8tc7ch_1130",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 241,
          "y": 581,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 61
        },
        {
          "id": "layer_mp8tc7jm_1131",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 241,
          "y": 595,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 62
        },
        {
          "id": "layer_mp8tc7q3_1132",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 241,
          "y": 608,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 63
        },
        {
          "id": "layer_mp8tc84k_1133",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 240,
          "y": 628,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 64
        },
        {
          "id": "layer_mp8tc8bt_1134",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 240,
          "y": 641,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 65
        },
        {
          "id": "layer_mp8tc8if_1135",
          "type": "text",
          "name": "Text copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy copy",
          "src": null,
          "x": 240,
          "y": 653,
          "w": 83,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Text",
          "fontSize": 12,
          "color": "#0a3156",
          "locked": false,
          "z": 66
        }
      ]
    },
    "venueTemplate": {
      "id": "page_venue_1",
      "name": "Venue 1",
      "stage": {
        "width": 390,
        "height": 844
      },
      "layers": [
        {
          "id": "layer_mp8tgbxg_1136",
          "type": "image",
          "name": "Venue 1 UI.png",
          "src": "blob:null/b21912ff-86d4-4ca6-91d9-c109029f3d14",
          "x": 0,
          "y": 0,
          "w": 390,
          "h": 844,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 0,
          "assetCategory": "Imported"
        },
        {
          "id": "layer_mp784cpo_1027",
          "type": "image",
          "name": "Repaired Stamp",
          "src": "assets/garage_directory_assets_repaired_stamp.webp",
          "x": 221,
          "y": 239,
          "w": 152,
          "h": 91,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": true,
          "z": 1,
          "assetCategory": "Garage Directory Assets"
        },
        {
          "id": "layer_mp787oxv_1031",
          "type": "text",
          "name": "Venue Name",
          "src": null,
          "x": 50,
          "y": 262,
          "w": 175,
          "h": 42,
          "r": 0,
          "opacity": 1,
          "text": "Venue Name",
          "fontSize": 25,
          "color": "#0a3156",
          "locked": false,
          "z": 2
        },
        {
          "id": "layer_mp789ync_1033",
          "type": "image",
          "name": "Exhaust Broken",
          "src": "assets/component_assets_exhaust_broken.png",
          "x": 41,
          "y": 337,
          "w": 121,
          "h": 97,
          "r": 0,
          "opacity": 1,
          "text": "TEXT",
          "fontSize": 28,
          "color": "#0a3156",
          "locked": false,
          "z": 3,
          "assetCategory": "Component Assets"
        },
        {
          "id": "layer_mp78c3x2_1036",
          "type": "text",
          "name": "Summary Text Location",
          "src": null,
          "x": 186,
          "y": 328,
          "w": 135,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Summary Text Location",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 4
        },
        {
          "id": "layer_mp78d0j5_1038",
          "type": "text",
          "name": "Address Text Location",
          "src": null,
          "x": 186,
          "y": 396,
          "w": 134,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Address Text Location",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 5
        },
        {
          "id": "layer_mp78gj6o_1039",
          "type": "text",
          "name": "Address Text Location copy",
          "src": null,
          "x": 186,
          "y": 407,
          "w": 134,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Address Text Location",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 6
        },
        {
          "id": "layer_mp78gldr_1040",
          "type": "text",
          "name": "Address Text Location copy copy",
          "src": null,
          "x": 186,
          "y": 419,
          "w": 134,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Address Text Location",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 7
        },
        {
          "id": "layer_mp78hy2n_1041",
          "type": "text",
          "name": "Summary Text Location copy",
          "src": null,
          "x": 186,
          "y": 341,
          "w": 135,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Summary Text Location",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 8
        },
        {
          "id": "layer_mp78hyrm_1042",
          "type": "text",
          "name": "Summary Text Location copy copy",
          "src": null,
          "x": 186,
          "y": 353,
          "w": 135,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Summary Text Location",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 9
        },
        {
          "id": "layer_mp78hz8a_1043",
          "type": "text",
          "name": "Summary Text Location copy copy copy",
          "src": null,
          "x": 186,
          "y": 364,
          "w": 135,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Summary Text Location",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 10
        },
        {
          "id": "layer_mp78in9j_1044",
          "type": "text",
          "name": "Food Hours Monday",
          "src": null,
          "x": 211,
          "y": 459,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Food Hours Monday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 11
        },
        {
          "id": "layer_mp78jcfz_1045",
          "type": "text",
          "name": "Food Hours Tuesday",
          "src": null,
          "x": 210,
          "y": 469,
          "w": 109,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Food Hours Tuesday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 12
        },
        {
          "id": "layer_mp78kjdf_1046",
          "type": "text",
          "name": "Food Hours Wednesday",
          "src": null,
          "x": 213,
          "y": 479,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Food Hours Wednesday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 13
        },
        {
          "id": "layer_mp78koef_1047",
          "type": "text",
          "name": "Food Hours Thursday",
          "src": null,
          "x": 213,
          "y": 489,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Food Hours Thursday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 14
        },
        {
          "id": "layer_mp78ksbp_1048",
          "type": "text",
          "name": "Food Hours Friday",
          "src": null,
          "x": 212,
          "y": 499,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Food Hours Friday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 15
        },
        {
          "id": "layer_mp78kuw8_1049",
          "type": "text",
          "name": "Food Hours Saturday",
          "src": null,
          "x": 212,
          "y": 509,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Food Hours Saturday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 16
        },
        {
          "id": "layer_mp78kxco_1050",
          "type": "text",
          "name": "Food Hours Sunday",
          "src": null,
          "x": 211,
          "y": 518,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Food Hours Sunday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 17
        },
        {
          "id": "layer_mp78nols_1052",
          "type": "text",
          "name": "Opening Hours Monday",
          "src": null,
          "x": 64,
          "y": 459,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Opening Hours Monday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 18
        },
        {
          "id": "layer_mp78o97i_1053",
          "type": "text",
          "name": "Opening Hours Tuesday",
          "src": null,
          "x": 65,
          "y": 469,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Opening Hours Tuesday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 19
        },
        {
          "id": "layer_mp78oe4u_1054",
          "type": "text",
          "name": "Opening Hours Wednesday",
          "src": null,
          "x": 71,
          "y": 479,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Opening Hours Wednesday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 20
        },
        {
          "id": "layer_mp78om58_1056",
          "type": "text",
          "name": "Opening Hours Friday",
          "src": null,
          "x": 61,
          "y": 499,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Opening Hours Friday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 21
        },
        {
          "id": "layer_mp78ot6h_1058",
          "type": "text",
          "name": "Opening Hours Saturday",
          "src": null,
          "x": 66,
          "y": 510,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Opening Hours Saturday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 22
        },
        {
          "id": "layer_mp78oxwe_1059",
          "type": "text",
          "name": "Opening Hours Sunday",
          "src": null,
          "x": 63,
          "y": 519,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Opening Hours Sunday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 23
        },
        {
          "id": "layer_mp78p3lg_1060",
          "type": "text",
          "name": "Notes Line 1",
          "src": null,
          "x": 59,
          "y": 546,
          "w": 264,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Notes Line 1",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 24
        },
        {
          "id": "layer_mp78pceo_1061",
          "type": "text",
          "name": "Notes Line 2",
          "src": null,
          "x": 42,
          "y": 556,
          "w": 274,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Notes Line 2",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 25
        },
        {
          "id": "layer_mp78qdk3_1062",
          "type": "text",
          "name": "Notes Line 3",
          "src": null,
          "x": 41,
          "y": 566,
          "w": 274,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Notes Line 3",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 26
        },
        {
          "id": "layer_mp78qhfy_1063",
          "type": "text",
          "name": "Website Address",
          "src": null,
          "x": 73,
          "y": 586,
          "w": 248,
          "h": 11,
          "r": 0,
          "opacity": 1,
          "text": "Website Address",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 27
        },
        {
          "id": "layer_mp78qrln_1064",
          "type": "text",
          "name": "Phone Number",
          "src": null,
          "x": 70,
          "y": 604,
          "w": 248,
          "h": 11,
          "r": 0,
          "opacity": 1,
          "text": "Phone Number",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 28
        },
        {
          "id": "layer_mp78quq7_1065",
          "type": "text",
          "name": "Email Address",
          "src": null,
          "x": 69,
          "y": 625,
          "w": 248,
          "h": 11,
          "r": 0,
          "opacity": 1,
          "text": "Email Address",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 29
        },
        {
          "id": "layer_mp78sqgm_1066",
          "type": "text",
          "name": "Opening Hours Thursday",
          "src": null,
          "x": 67,
          "y": 489,
          "w": 105,
          "h": 10,
          "r": 0,
          "opacity": 1,
          "text": "Opening Hours Thursday",
          "fontSize": 7,
          "color": "#0a3156",
          "locked": false,
          "z": 30
        }
      ]
    }
  },
  "firebaseConfig": {
    "apiKey": "AIzaSyBSSekdM7t9zc_ee0kQ5xSBFYNvRN53PV0",
    "authDomain": "the-restoration-route.firebaseapp.com",
    "projectId": "the-restoration-route",
    "storageBucket": "the-restoration-route.firebasestorage.app",
    "messagingSenderId": "878380399095",
    "appId": "1:878380399095:web:6a16f26fedce5f1f9c96f2",
    "measurementId": "G-0PLZQ6B8HT"
  },
  "appUrl": "https://the-piston-club.github.io/The-Restoration-Route",
  "scanTokenHashes": {
    "9af115613992fb1dd35e7281d5dfcf509fcac5b9089ce9941406226a3e532ec4": "piston-club",
    "c1e8ab555f006ceca5d6b98e2f19bbc2c2ac1b67704e60e7648e3c04d9a6ce8d": "oily-rag",
    "b841cf0c7e30d81cb4463d702471bbc5d648bc10c9603e96d30f0b2c42991937": "seven-mile",
    "9d1bf0ae7d55f2b000b313caf87abc58ccda56856affad05ac427692ace6bc34": "mr-watsons",
    "92aeb71e6e5f9ff83f9b4b05b06dec0e314dcb61b2459bdff704944f72281a6b": "gilks-garage",
    "51417b1981705df7e4d9ba9d6de5c658d9caaca7a7645d77affc078ccc3f4203": "long-itch-diner",
    "e5cb292c5b642a193fb299b6a8f2db415aec944e295e352ec5e513d42d835eab": "pats-baps",
    "1fe03a5692a95322243b80440d5744fade6c875295aceb220eaf3b1ad2f1b02b": "the-man-cave"
  },
  "privateMarkerPatterns": {
    "1010001011110010111010101100100001000110011001110": "piston-club",
    "1001001010001101100101001001010100000110011110010": "oily-rag",
    "1000011001001111011110000100001011110110011000110": "seven-mile",
    "1010101000101110010011010001000110110100111100010": "mr-watsons",
    "1010011011100010000001100111010111011110011111010": "gilks-garage",
    "1001011011100000111111001000001110011101111101010": "long-itch-diner",
    "1001101010001101111010110001111110101001111111010": "pats-baps",
    "1000111001111111000111011101011001101001111010110": "the-man-cave"
  },
  "usernameRules": {
    "pattern": "^[A-Za-z0-9_-]{3,20}$",
    "blocked": [
      "fuck",
      "shit",
      "cunt",
      "nigger",
      "nigga",
      "bitch",
      "twat",
      "wanker",
      "fag",
      "faggot",
      "retard",
      "nonce",
      "admin",
      "staff",
      "moderator",
      "thepistonclub",
      "pistonclub",
      "restorationroute"
    ]
  },
  "terms": {
    "organiser": "The Piston Club",
    "contactEmail": "chip@thepistonclub.co.uk",
    "prize": "To be announced",
    "endDate": "To be announced"
  },
  "routeMapUrl": "https://www.google.com/maps/d/embed?mid=1WlxrelHk9Yn35XKqfW9DmSKJyNv6D8w&hl=en&ehbc=2E312F",
  "banterUrl": "https://www.justgiving.com/crowdfunding/burtonbanter?utm_medium=CF&utm_source=CL",
  "banterWidgetUrl": "https://widgets.justgiving.com/crowdfunding-pledge-box/?id=burtonbanter&layout=large&showStory=true",
  "tabAssetOverrides": {
    "assets/garage_directory_assets_directory_tab_buttons_garage_directory_tab_button.png": "assets/garage_directory_assets_directory_tab_buttons_garage_directory_tab_button.webp",
    "assets/garage_directory_assets_directory_tab_buttons_the_piston_club_tab_button.png": "assets/garage_directory_assets_directory_tab_buttons_the_piston_club_tab_button.webp",
    "assets/garage_directory_assets_directory_tab_buttons_mr_watsons_tab_button.png": "assets/garage_directory_assets_directory_tab_buttons_mr_watsons_tab_button.webp",
    "assets/garage_directory_assets_directory_tab_buttons_gilks_garage_tab_button.png": "assets/garage_directory_assets_directory_tab_buttons_gilks_garage_tab_button.webp",
    "assets/garage_directory_assets_directory_tab_buttons_oily_rag_tab_button.png": "assets/garage_directory_assets_directory_tab_buttons_oily_rag_tab_button.webp",
    "assets/garage_directory_assets_directory_tab_buttons_the_long_itch_diner_tab_button.png": "assets/garage_directory_assets_directory_tab_buttons_the_long_itch_diner_tab_button.webp",
    "assets/garage_directory_assets_directory_tab_buttons_pats_baps_tab_button.png": "assets/garage_directory_assets_directory_tab_buttons_pats_baps_tab_button.webp",
    "assets/garage_directory_assets_directory_tab_buttons_seven_mile_tab_button.png": "assets/garage_directory_assets_directory_tab_buttons_seven_mile_tab_button.webp"
  }
};
